# Generated by Django 4.0 on 2021-12-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('layoffs', 'Layoffs'), ('hiring_freeze', 'Hiring Freeze'), ('hiring', 'Hiring')], default='hiring', max_length=30)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('application_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
